#!/usr/bin/env node
import fs from 'fs';
import path from 'path';

const ROOT = process.cwd();
const SRC_DIR = path.join(ROOT, 'assets', '_src', 'js');
const parts = [
  'chunk_subject_expansion_wave58_secondary_math_7_9.js',
  'chunk_subject_expansion_wave59_physics_chemistry_7_9.js'
];
const outName = 'chunk_subject_expansion_wave89c_secondary_stem_7_9.js';

function readSource(name){
  const file = path.join(SRC_DIR, name);
  if (!fs.existsSync(file)) throw new Error(`Missing source: ${name}`);
  return fs.readFileSync(file, 'utf8').trim() + '\n';
}

const header = [
  '/* generated by tools/build_scripts_budget_wave89c.mjs */',
  '/* wave89c: secondary STEM merge for grades 7-9 */',
  `/* parts: ${parts.join(', ')} */`,
  ''
].join('\n');
const body = parts.map(readSource).join('\n');
const footer = `\n(function(){\n  if (typeof window === 'undefined') return;\n  window.__wave89cSecondaryStemMerge = {\n    version: 'wave89c',\n    parts: ['wave58-secondary-math-7-9', 'wave59-physics-chemistry-7-9']\n  };\n})();\n`;
const output = header + body + footer;
fs.writeFileSync(path.join(SRC_DIR, outName), output);
console.log(JSON.stringify({ out: outName, parts, bytes: Buffer.byteLength(output) }, null, 2));
